### ISSUE TITLE
Moonrang fails

### ISSUE THREAD

**Issue by orkaboy** [shenef/SoS-TAS#140]
As I routed Moorlands and onwards, I would frequently and very reliably see Moonrang getting into a bad state. Valere would launch the attack, try to deflect very early (before the enemy was even hit), then miss on the return.

At this point, the TAS presumably thinks that the spell is still casting? Either that or it thinks that Valere is still selectable. It ends up in a loop selecting between Zale and Garl, without actually committing to a new attack.

**Comment by Eein** [comment]
the loop between selecting zale and garl is what i believe to be the 'shadow character' issue, where it thinks theres more characters to consider than there actually is - i'll be updating this in the future to fix _read_players() in combat_manager

**Comment by Eein** [comment]
Not the shadow character issue. related to _read_back_to_slot, need to find a better way to confirm the attack has ended

**Comment by Eein** [comment]
Should be fixed by #158 - leaving this ticket open for tracking

**Comment by orkaboy** [comment]
I'd say we can close this now; the issue appears to be solved.
