### ISSUE TITLE
Properly implement boost

### ISSUE THREAD

**Issue by Eein** [shenef/SoS-TAS#147]
https://github.com/shenef/SoS-TAS/pull/146/files/69220fcdd9b259b752af75b9df8a60f9fb6d2f5a#diff-add6d15b02251e4c8d06350f7dea601a57dbe03bb41afefa262bbc093d8330c2R116-R122

Currently freezing the gui, but can be more clever and hit confirm until combat_controller.big_live_mana reaches the expected boost count.

**Comment by orkaboy** [comment]
Consider a small FSM + timer, and using the `toggle_` functions to set the buttons.
