### ISSUE TITLE
Move enemy/boost generation to reasoner 

### ISSUE THREAD

**Issue by Eein** [shenef/SoS-TAS#159]
This would allow controllers to use the reasoner context to modify/configure this more easily.

**Comment by Eein** [comment]
note to clean up: https://github.com/shenef/SoS-TAS/pull/158/files/a31c1ccc0fa5324e963c4283326414c5d21fd4cd#diff-9b09a1f3af97f50d37f1eb36e3a9ceef6be0a3e1d789426b415efe8405e54897

**Comment by orkaboy** [comment]
Note; I've made changes to this code when doing combat locks.
