### ISSUE TITLE
New Moonerang bug

### ISSUE THREAD

**Issue by orkaboy** [shenef/SoS-TAS#193]
With the latest code, I've observed the TAS trying to execute Moonerang, but getting stuck when trying to enter the skill menu. The TAS is stuck in the top level menu, hovering the Skill option.

Here's the log (the line a minute after the Moonerang is when combat ended after manual inputs):

![bild](https://github.com/shenef/SoS-TAS/assets/1805679/a726fb2d-3045-42cf-9aa8-9f8ff5f137fe)

**Comment by Eein** [comment]
ty... this looks like its resetting the combat controller.... weird. the next line would have been useful as well :P

we can probably fix this by resetting actions if no controller exists; but we also may need the fallback code to drop out of any command menus if there is no action.

**Comment by orkaboy** [comment]
> this looks like its resetting the combat controller

I don't think that's necessarily the case.if you are talking about the Finished combat/Setting New Combat Controller, that's after the combat finished with manual input, and isn't connected to the bug. Note timestamps.

**Comment by orkaboy** [comment]
This issue appears to be solved in the latest code.
