### ISSUE TITLE
Sunball and Pressure Cooker targeting

### ISSUE THREAD

**Issue by orkaboy** [shenef/SoS-TAS#229]
I checked and the Pressure Cooker attack that Garl has appears to have the same issue as Zale's Sunball (no valid target). We're not using it atm, but if we fix one we hopefully fix the other.

**Comment by Eein** [comment]
in this case, i just need to properly scan:
1. the acting character in the character list'
2. the ability being used in the ability list compared to the targeted ability

All of this is 'on my list' in preparation for optimizing battle
